#!/usr/bin/with-contenv bash

echo "*** nomad installer ***"

apt-get update && apt-get install -y software-properties-common
curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt-get update && apt-get install -y nomad

echo "export NOMAD_ADDR=http://nomad-client.nex.fyi:4646" >> /config/.bashrc
